### ISSUE TITLE
Request for bag file

### ISSUE THREAD

**Issue by 863217373** [tum-phoenix/drive_ros_localize_wheel_odometry#5]
Sir，I want to use this package, but I don't know the format of the bag file used by this package. So could update the bag file to this package. thank you very much.

**Comment by Phibedy** [comment]
It is written in the Readme of this project ;)
Github has a great search function (code/commits): https://github.com/search?q=org%3Atum-phoenix+VehicleEncoder&type=Code

**Comment by fabolhak** [comment]
Here you can find an example bag:
[test.bag.zip](https://github.com/tum-phoenix/drive_ros_localize_wheel_odometry/files/3310091/test.bag.zip)

With [this](https://github.com/tum-phoenix/drive_ros_localize_wheel_odometry/blob/master/config/ftm_rc_car_1.yaml) parameters it should drive approximately a rectangle.

You need the `VehicleEncoder` and `EncoderLinear` message definitions from: https://github.com/tum-phoenix/drive_ros_msgs
